name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create build directory
        run: mkdir -p build

      - name: Verify build directory exists
        run: ls -la build

      - name: Zip files for deployment
        run: zip -r build/function.zip . -x '*.git*' -x 'terraform/*' -x 'build/*' -x '.idea/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda-function
          path: build/function.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lambda-function

      - name: Deploy to AWS Lambda
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code --function-name fastifyAPIOnAWSLambda --zip-file fileb://function.zip
